// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview An AI agent that suggests prescriptions based on patient data.
 *
 * - generatePrescriptionSuggestions - A function that generates prescription suggestions.
 * - GeneratePrescriptionSuggestionsInput - The input type for the generatePrescriptionSuggestions function.
 * - GeneratePrescriptionSuggestionsOutput - The return type for the generatePrescriptionSuggestions function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GeneratePrescriptionSuggestionsInputSchema = z.object({
  patientHistory: z
    .string()
    .describe('The patient medical history, including past illnesses and medications.'),
  currentSymptoms: z.string().describe('The current symptoms of the patient.'),
  patientAge: z.number().describe('The age of the patient.'),
});
export type GeneratePrescriptionSuggestionsInput = z.infer<typeof GeneratePrescriptionSuggestionsInputSchema>;

const GeneratePrescriptionSuggestionsOutputSchema = z.object({
  suggestedPrescriptions: z
    .string()
    .describe('A list of suggested prescriptions based on the patient data.'),
  recommendations: z.string().describe('Additional recommendations for the doctor.'),
});
export type GeneratePrescriptionSuggestionsOutput = z.infer<typeof GeneratePrescriptionSuggestionsOutputSchema>;

export async function generatePrescriptionSuggestions(input: GeneratePrescriptionSuggestionsInput): Promise<GeneratePrescriptionSuggestionsOutput> {
  return generatePrescriptionSuggestionsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generatePrescriptionSuggestionsPrompt',
  input: {schema: GeneratePrescriptionSuggestionsInputSchema},
  output: {schema: GeneratePrescriptionSuggestionsOutputSchema},
  prompt: `You are an AI assistant helping doctors make informed decisions about prescriptions.

  Based on the patient's medical history, current symptoms, and age, suggest potential prescriptions and recommendations.

  Patient History: {{{patientHistory}}}
  Current Symptoms: {{{currentSymptoms}}}
  Patient Age: {{{patientAge}}}

  Provide a list of suggested prescriptions and any additional recommendations for the doctor to consider.
  Format the output as a JSON object.
  `,config: {
    safetySettings: [
      {
        category: 'HARM_CATEGORY_HATE_SPEECH',
        threshold: 'BLOCK_ONLY_HIGH',
      },
      {
        category: 'HARM_CATEGORY_DANGEROUS_CONTENT',
        threshold: 'BLOCK_NONE',
      },
      {
        category: 'HARM_CATEGORY_HARASSMENT',
        threshold: 'BLOCK_MEDIUM_AND_ABOVE',
      },
      {
        category: 'HARM_CATEGORY_SEXUALLY_EXPLICIT',
        threshold: 'BLOCK_LOW_AND_ABOVE',
      },
    ],
  },
});

const generatePrescriptionSuggestionsFlow = ai.defineFlow(
  {
    name: 'generatePrescriptionSuggestionsFlow',
    inputSchema: GeneratePrescriptionSuggestionsInputSchema,
    outputSchema: GeneratePrescriptionSuggestionsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
